#!/bin/bash

hostname="mystery-box"

if [[ -f /etc/hostname ]]; then
    hostname=$(cat /etc/hostname)
fi

printf "Username: "
read username

sudo useradd -m ${username}
sudo usermod -aG guests ${username}

echo "Set password for ${username}"
sudo passwd ${username}

echo "Welcome to ${hostname}!"
exit